export const TABLES = Object.freeze({
    USERS: "users",
    ROLES: "roles",
    USER_ROLES: "user_roles",
    USER_SCOPE_ROLES: "user_scope_roles",
    STUDENT_PROFILES: "student_profiles",
    OPPORTUNITIES: "opportunities",
    EMAIL_GROUPS: "email_groups",
    EMAIL_GROUP_MEMBERSHIPS: "email_group_memberships",
    OPPORTUNITY_VISIBILITY_RULES: "opportunity_visibility_rules",
    WORKFLOW_STAGES: "workflow_stages",
    APPLICATIONS: "applications",
    APPLICATION_STUDENT_SNAPSHOT: "application_student_snapshot",
    APPLICATION_DOCUMENTS: "application_documents",
    APPLICATION_REVIEWS: "application_reviews",
    APPLICATION_DECISIONS: "application_decisions",
    APPLICATION_REMARKS: "application_remarks",
    TIMELINE_EVENTS: "timeline_events",
    CHAT_THREADS: "chat_threads",
    CHAT_THREAD_PARTICIPANTS: "chat_thread_participants",
    CHAT_MESSAGES: "chat_messages",
});
